#include "class_character.h"
#include "class_symbol.h"
#include "class_class.h"
#include "integers.h"
#include "symbols.h"

/* We define all ASCII characters at compile time, because characters
   are used to build string that we also need at compile time.
 */

define_character(NUL, 0);
define_character(SOH, 1);
define_character(STX, 2);
define_character(ETX, 3);
define_character(EOT, 4);
define_character(ENQ, 5);
define_character(ACK, 6);
define_character(BEL, 7);
define_character(BS, 8);
define_character(TAB, 9);
define_character(LF, 10);
define_character(VT, 11);
define_character(FF, 12);
define_character(CR, 13);
define_character(SO, 14);
define_character(SI, 15);
define_character(DLE, 16);
define_character(DC1, 17);
define_character(DC2, 18);
define_character(DC3, 19);
define_character(DC4, 20);
define_character(NAK, 21);
define_character(SYN, 22);
define_character(ETB, 23);
define_character(CAN, 24);
define_character(EM, 25);
define_character(SUB, 26);
define_character(ESC, 27);
define_character(FS, 28);
define_character(GS, 29);
define_character(RS, 30);
define_character(US, 31);

define_character(space, 32);
define_character(exclamation_mark, 33);
define_character(double_quote, 34);
define_character(hash_sign, 35);
define_character(dollar_sign, 36);
define_character(percent_sign, 37);
define_character(ampersand, 38);
define_character(single_quote, 39);
define_character(left_parenthesis, 40);
define_character(right_parenthesis, 41);
define_character(asterisk, 42);
define_character(plus_sign, 43);
define_character(comma, 44);
define_character(minus_sign, 45);
define_character(dot, 46);
define_character(slash, 47);
define_character(0, 48);
define_character(1, 49);
define_character(2, 50);
define_character(3, 51);
define_character(4, 52);
define_character(5, 53);
define_character(6, 54);
define_character(7, 55);
define_character(8, 56);
define_character(9, 57);
define_character(colon, 58);
define_character(semicolon, 59);
define_character(less_than_sign, 60);
define_character(equal_sign, 61);
define_character(greater_than_sign, 62);
define_character(question_mark, 63);
